"""Shared Python foundations for Zayd services."""

from .auth import (
    AccessTokenClaims,
    AuthError,
    AuthResult,
    AuthService,
    AuthTokens,
    UserPublic,
    hash_password,
    hash_token,
    verify_password,
)
from .database import (
    AbstractDocumentRepository,
    AbstractIncidentRepository,
    AbstractSourceRepository,
    AbstractUnitOfWork,
    AbstractUserRepository,
    Base,
    SQLAlchemyDocumentRepository,
    SQLAlchemyIncidentRepository,
    SQLAlchemySourceRepository,
    SQLAlchemyUnitOfWork,
    SQLAlchemyUserRepository,
    get_sessionmaker,
    seed_demo_data,
)
from .enums import (
    DocumentStatus,
    EvidenceStatus,
    IncidentSeverity,
    IncidentStatus,
    PermissionState,
    ProviderStatus,
    ReviewDecision,
    ReviewTaskStatus,
    RiskLevel,
)
from .exceptions import (
    ConcurrencyConflictError,
    InvalidStateTransitionError,
    MissingTransitionMetadataError,
    StateTransitionError,
)
from .guest import (
    GuestError,
    GuestService,
    GuestSessionInfo,
    hash_guest_token,
)
from .health import HealthStatus
from .logging import get_logger
from .mfa import (
    PRIVILEGED_ROLE_NAMES,
    MfaChallenge,
    MfaEnrollment,
    MfaError,
    MfaResetChannel,
    MfaService,
    generate_totp,
    verify_totp,
)
from .rbac import (
    ROLE_PERMISSION_MATRIX,
    Permission,
    RbacError,
    RbacService,
    UserPrincipal,
)
from .retrievability import can_activate_embedding, is_document_retrievable
from .settings import ServiceSettings
from .state_machines import (
    DocumentStateMachine,
    IncidentStateMachine,
    ReviewTaskStateMachine,
    TransitionMetadata,
)

__all__ = [
    "HealthStatus",
    "ServiceSettings",
    "get_logger",
    "DocumentStatus",
    "ReviewDecision",
    "PermissionState",
    "EvidenceStatus",
    "RiskLevel",
    "IncidentSeverity",
    "IncidentStatus",
    "ReviewTaskStatus",
    "ProviderStatus",
    "StateTransitionError",
    "InvalidStateTransitionError",
    "MissingTransitionMetadataError",
    "ConcurrencyConflictError",
    "TransitionMetadata",
    "DocumentStateMachine",
    "ReviewTaskStateMachine",
    "IncidentStateMachine",
    "is_document_retrievable",
    "can_activate_embedding",
    "Base",
    "AbstractUserRepository",
    "SQLAlchemyUserRepository",
    "AbstractSourceRepository",
    "SQLAlchemySourceRepository",
    "AbstractDocumentRepository",
    "SQLAlchemyDocumentRepository",
    "AbstractIncidentRepository",
    "SQLAlchemyIncidentRepository",
    "AbstractUnitOfWork",
    "SQLAlchemyUnitOfWork",
    "get_sessionmaker",
    "seed_demo_data",
    "AccessTokenClaims",
    "AuthError",
    "AuthResult",
    "AuthService",
    "AuthTokens",
    "UserPublic",
    "hash_password",
    "hash_token",
    "verify_password",
    "GuestError",
    "GuestService",
    "GuestSessionInfo",
    "hash_guest_token",
    "Permission",
    "RbacError",
    "RbacService",
    "ROLE_PERMISSION_MATRIX",
    "UserPrincipal",
    "MfaChallenge",
    "MfaEnrollment",
    "MfaError",
    "MfaResetChannel",
    "MfaService",
    "PRIVILEGED_ROLE_NAMES",
    "generate_totp",
    "verify_totp",
]
